### ISSUE TITLE
github : The webhook problem cannot be used properly.

### ISSUE THREAD

**Issue by myzf** [spring-cloud/spring-cloud-bus#118]
Question
The following is my config-server configuration.
```
<parent>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-parent</artifactId>
        <version>2.0.1.RELEASE</version>
    </parent>
```

 ```
   <properties>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <project.reporting.outputEncoding>UTF-8</project.reporting.outputEncoding>
        <java.version>1.8</java.version>
        <spring-cloud.version>Finchley.RC1</spring-cloud.version>
    </properties>

 <dependency>
            <groupId>org.springframework.cloud</groupId>
            <artifactId>spring-cloud-config-server</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.cloud</groupId>
            <artifactId>spring-cloud-starter-netflix-eureka-client</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-test</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.springframework.cloud</groupId>
            <artifactId>spring-cloud-starter-bus-amqp</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.cloud</groupId>
            <artifactId>spring-cloud-config-monitor</artifactId>
        </dependency>
```

Bug report
1. When i use json
**Request URL: http://180.42.55.89:8091/actuator/bus-refresh
Request method: POST
content-type: application/json
Expect: 
User-Agent: GitHub-Hookshot/d269590
X-GitHub-Delivery: edee836e-590c-11e8-9677-ca3b7789fb0b
X-GitHub-Event: push**
Response400
Headers
Connection: close
Content-Length: 495
Content-Type: application/json;charset=UTF-8
Date: Wed, 16 May 2018 15:37:42 GMT
Transfer-Encoding: chunked
Body
{"timestamp":"2018-05-16T15:37:42.734+0000","status":400,"error":"Bad Request","message":"JSON parse error: Cannot deserialize instance of `java.lang.String` out of START_ARRAY token; nested exception is com.fasterxml.jackson.databind.exc.MismatchedInputException: Cannot deserialize instance of `java.lang.String` out of START_ARRAY token\n at [Source: (PushbackInputStream); line: 1, column: 288] (through reference chain: java.util.LinkedHashMap[\"commits\"])","path":"/actuator/bus-refresh"}

The Java console shows this error.
**Failed to read HTTP message: org.springframework.http.converter.HttpMessageNotReadableException: JSON parse error: Cannot deserialize instance of `java.lang.String` out of START_ARRAY token; nested exception is com.fasterxml.jackson.databind.exc.MismatchedInputException: Cannot deserialize instance of `java.lang.String` out of START_ARRAY token
 at [Source: (PushbackInputStream); line: 1, column: 288] (through reference chain: java.util.LinkedHashMap["commits"])**

2.When i use form
It reported 415 errors.

I'm trying to make a direct request with the post, the body is empty, the json format, there's no problem, the program is normal. The judgment is that after carrying the body, there is no normal parsing of json on this side of the program.
How can I fix this problem, it has been bothering me for a long time?

I have seen a similar mistake before, saying that it is ok to add the 
```
<dependency>
            <groupId>org.springframework.cloud</groupId>
            <artifactId>spring-cloud-config-monitor</artifactId>
        </dependency>
```,
 but now that I have added it, I have no effect. It is the same mistake to ask that question before.


I hope the handsome body can help me out.

**Comment by spencergibb** [comment]
`/bus-refresh` does not take a body. Only `/monitor` does.

**Comment by myzf** [comment]
Understand what you mean, I changed to /monitor, my service configuration center can be accessed normally, but there is a problem, the client can not synchronize configuration, any client can not. I looked at the same question before. Is it necessary that the server or the client add a configuration to solve the problem that the client can not accept to the synchronization problem?
我的客户端配置如下

```

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
spring:
  application:
    name: order
  redis:
    host: 127.0.0.1
    password: 123456
  rabbitmq:
    host: wx.myzf.xyz
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://127.0.0.1:3306/test?characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: true
management:
  security:
    enabled: false
  endpoints:
    web:
      exposure:
        include: bus-refresh
```
