### ISSUE TITLE
Received remote refresh request. Keys refreshed []

### ISSUE THREAD

**Issue by dqqzj** [spring-cloud/spring-cloud-bus#141]
```
<properties>
        <java.version>1.8</java.version>
        <spring-cloud.version>Greenwich.M3</spring-cloud.version>
    </properties>
```

my application.yml is here :

```
server:
  port: 8888
spring:
  cloud:
    config:
      server:
        git:
          uri: http://xxxxxx:3000/xiangmingchao/springcloud2.0.git
          username: xiangmingchao
          password: Deloitte12
          search-paths: config-repo
      label: master
    bus:
      trace:
        enabled: true
  application:
    name: config-server
  rabbitmq:
    addresses: 192.168.20.10:5672,192.168.20.4:5672,192.168.20.19:5672
    username: admin
    password: Deloitte12
eureka:
  client:
    service-url:
      defaultZone: http://deloitte:deloitte@192.168.20.20:8761/eureka/,http://deloitte:deloitte@192.168.20.24:8761/eureka/
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
management:
  endpoints:
    web:
      exposure:
        include: bus-refresh

this is the bug : 2018-12-11 18:16:15.398  INFO 24678 --- [nio-8888-exec-6] o.s.cloud.bus.event.RefreshListener      : Received remote refresh request. Keys refreshed []
2018-12-11 18:16:15.400  INFO 24678 --- [nfoReplicator-0] com.netflix.discovery.DiscoveryClient    : DiscoveryClient_CONFIG-SERVER/192.168.20.24:8888: registering service...
2018-12-11 18:16:15.411  INFO 24678 --- [nfoReplicator-0] com.netflix.discovery.DiscoveryClient    : DiscoveryClient_CONFIG-SERVER/192.168.20.24:8888 - registration status: 204
tail: config.log: file truncated
2018-12-11 18:17:57.886  INFO 25038 --- [           main] trationDelegate$BeanPostProcessorChecker : Bean 'configurationPropertiesRebinderAutoConfiguration' of type [org.springframework.cloud.autoconfigure.ConfigurationPropertiesRebinderAutoConfiguration$$EnhancerBySpringCGLIB$$4325ab32] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
Activate the edition of the editorial spring cloudconfig Japanese springcloud bus rabbitMQ progressive matching concurrency / actuator / bus - refresh
```

**Comment by spencergibb** [comment]
Can you provide steps to recreate the problem? Better yet, can you provide a [complete, minimal, verifiable sample](https://stackoverflow.com/help/mcve) that reproduces the problem?  It should be available as a GitHub (or similar) project or attached to this issue as a zip file.

**Comment by dqqzj** [comment]
well  i provide my all projects configurations for you!  I only used these components. there are bus ,config config-server and rabbitMQ. You  should know what i want to do

**Comment by dqqzj** [comment]
project version is below:
```
<properties>
        <java.version>1.8</java.version>
        <spring-cloud.version>Greenwich.M3</spring-cloud.version>
    </properties>
``` 
and spring-boot version is 2.1.1.RELEASE

**Comment by dqqzj** [comment]
this is my config-server application.yml.
```
server:
  port: 8888
spring:
  cloud:
    config:
      server:
```
        git:
          uri: http://xxx:3000/xiangmingchao/springcloud2.0.git
          username: xiangmingchao
          password: Deloitte12
          search-paths: config-repo
      label: master
    bus:
      trace:
        enabled: true
  application:
    name: config-server
  rabbitmq:
    addresses: 192.168.20.10:5672,192.168.20.4:5672,192.168.20.19:5672
    username: admin
    password: Deloitte12
eureka:
  client:
    service-url:
      defaultZone: http://deloitte:deloitte@192.168.20.20:8761/eureka/,http://deloitte:deloitte@192.168.20.24:8761/eureka/
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
management:
  endpoints:
    web:
      exposure:
        include: bus-refresh

**Comment by dqqzj** [comment]
here is my config-client bootstrap.yml.
```
server:
  port: 8762
spring:
  application:
    name: zuul
  rabbitmq:
    addresses: 192.168.20.10:5672,192.168.20.4:5672,192.168.20.19:5672
    username: admin
    password: Deloitte12
  #配置中心
  cloud:
    config:
      label: master
      discovery:
        enabled: true
        service-id: config-server
      fail-fast: true
      profile: dev
      retry:
        max-attempts: 3
        multiplier: 1.2
        initial-interval: 1000
        max-interval: 2000
    bus:
      trace:
        enabled: true
eureka:
  client:
    service-url:
      defaultZone: http://deloitte:deloitte@10.173.48.104:8761/eureka/,http://deloitte:deloitte@10.173.48.103:8761/eureka/
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}

```

**Comment by dqqzj** [comment]
my config-client's test controller is below.
```
package com.deloitte.iddc.zuul.controller;

import org.springframework.beans.factory.annotation.Value;
import org.springframework.cloud.context.config.annotation.RefreshScope;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RestController;

/**
 * @Auther: zqin
 * @Date: 11/12/2018 11:04
 * @Description:
 */
@RefreshScope
@RestController
public class ConfigClientController {

    @Value("${feign.compression.request.min-request-size}")
    private String size;

    @GetMapping("/size")
    public String getProfile() {
        return this.size;
    }

}

```

**Comment by dqqzj** [comment]
my config-repo is here. its name is zuul-dev.yml.
```
#开启动态网关服务发现
ribbon:
  eureka:
    enabled: true
  ReadTimeout: 30000
  ConnectTimeout: 30000
#避免第一次调用失败
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000
#请求和响应GZIP压缩支持
feign:
  compression:
    request:
      enabled: true
      mime-types: text/xml,application/xml,application/json
      min-request-size: 6666
    response:
      enabled: true
  hystrix:
    enabled: true
#zuul 超时时间
zuul:
  host:
    socket-timeout-millis: 60000
    connect-timeout-millis: 60000
management:
  endpoints:
    web:
      exposure:
        include: bus-refresh
```
