### ISSUE TITLE
Add possibility to configure brokers using spring.cloud.bus.*

### ISSUE THREAD

**Issue by armsargis** [spring-cloud/spring-cloud-bus#226]
I have project with already configured amqp but for cloud bus want to use separate virtual host with its own username/password

I think its nice to have possibility to configure brokers using separate config path to be able isolate modules.

If you think idea is nice I can prepare PR.

**Comment by spencergibb** [comment]
I'm not sure I understand why this is needed. Streams already support multiple binders.
/cc @olegz

**Comment by armsargis** [comment]
Sorry and let try to explain with example:

In my current project I already have:

```
spring.rabbitmq.host=hostnname
spring.rabbitmq.username=user
spring.rabbitmq.password=password
spring.rabbitmq.virtual-host=/production
```
now I want to use spring-cloud-bus also in my project with amqp but with configs:

```
spring.rabbitmq.host=hostnname
spring.rabbitmq.username=cloud
spring.rabbitmq.password=bus
spring.rabbitmq.virtual-host=/bus
```

to be able to do it I am suggesting to have possibility to defined configuration using:

```yaml
spring:
  cloud:
    bus:
      rabbitmq:
        host: localhost
        username: cwb
        password: cwb
        virtual-host: /cwb
```
