### ISSUE TITLE
Why Spring Cloud Bus not use ${spring.cloud.bus.destination}  as Consumer Topic?

### ISSUE THREAD

**Issue by iwfun** [spring-cloud/spring-cloud-bus#253]
```
spring.cloud:
  bus:
    destination: bus-topic
  stream:
    default-binder: kafka
    kafka:
      binder:
        brokers: localhost:9092
        auto-create-topics: true
    bindings:
      springCloudBusInput:
        destination: ${spring.cloud.bus.destination}
        group: iam-gateway
```

I have to define ${spring.cloud.stream.bindings.springCloudBusInput.destination} like that.
Why not use ${spring.cloud.bus.destination}  as Consumer Topic like Producer？

spring cloud version：2020.0.2
