### ISSUE TITLE
Wrong destination in kafka bus

### ISSUE THREAD

**Issue by vbasem** [spring-cloud/spring-cloud-bus#72]
using the following cloud bus components
```gf
    compile('org.springframework.cloud:spring-cloud-starter-config:2.0.0.BUILD-SNAPSHOT')
    compile('org.springframework.cloud:spring-cloud-starter-bus-kafka:2.0.0.BUILD-SNAPSHOT')
```
when using the config server we found out that the writes were happening to the springCloudBusOutput topic while the client was reading from springCloudBus by default.

I could only overcome the issue by setting the bus explicitly in the client destination:

```yaml
spring:
  profiles:
    active: local
  application:
    name: ui-app
  cloud:
    bus:                                 
      enabled: true
      destination: springCloudBusOutput
```

Is this a bug or just a bad configuration?
